### ISSUE TITLE
Can not start program

### ISSUE THREAD

**Issue by ElPicador** [Mestelan/hn-queries-assignment#2] opened 2018-09-07 11:16 UTC
Whatever port I'm choosing, I always have a `java.net.BindException: Address already in use` exception, so I can't start the jar.

What did I miss:

```
» java -jar target/hn-query-mestelan.jar ~/Downloads/hn_logs.tsv -Dcom.algolia.assignment.server.port=4567
[main] INFO com.algolia.assignment.indexing.Repository - Indexed indexedQueries in 4594 ms.
[Thread-0] INFO org.eclipse.jetty.util.log - Logging initialized @4823ms to org.eclipse.jetty.util.log.Slf4jLog
[Thread-0] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
[Thread-0] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:8080
[Thread-0] INFO org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT, build timestamp: 2017-11-21T22:27:37+01:00, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
[Thread-0] INFO org.eclipse.jetty.server.session - DefaultSessionIdManager workerName=node0
[Thread-0] INFO org.eclipse.jetty.server.session - No SessionScavenger set, using defaults
[Thread-0] INFO org.eclipse.jetty.server.session - Scavenging every 600000ms
[Thread-0] ERROR spark.Spark - ignite failed
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:433)
	at java.base/sun.nio.ch.Net.bind(Net.java:425)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:225)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:334)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:302)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:238)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:397)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at spark.embeddedserver.jetty.EmbeddedJettyServer.ignite(EmbeddedJettyServer.java:149)
	at spark.Service.lambda$init$2(Service.java:549)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by Mestelan** [comment] 2018-09-07 12:30
Hello,

Your command is the correct one.
This is strange, I never met this issue, neither during the development process nor with the compiled jar. Sorry for the incovenience.

I cannot trace the problem back to any issues in the spark-java application:
https://stackoverflow.com/search?q=%5Bspark-java%5D+BindException%3A+Address+already+in+use
https://github.com/perwendel/spark/issues?utf8=%E2%9C%93&q=is%3Aissue+BindException%3A+Address+already+in+use

From your comment, I understand you never could start the server once? 
Not sure if this will help then, but what is the output for 
**netstat -laptune | grep 4567**
?

Is it practical for you to try and start the application from an IDE? Do you get the same error then?

**Comment by Mestelan** [comment] 2018-09-07 12:34
Also, which platform are you running on? 
I have tested the server to run OK, although only on 2 Linux Debian machines. Of course, we love Java for being platform-independent, but still, network issues might occur, especially in VMs, etc?

**Comment by ElPicador** [comment] 2018-09-07 12:37
I'm not on linux, so the `netstat` command won't work 😄 . But I've checked, before posting this issue, that the port `4567` was not used by something else.
For some reasons, it works in my IDE. I'll try it from there.

Thanks

**Comment by Mestelan** [comment] 2018-09-07 13:18
Well yes, I was sure you had tried. 
I thought **netstat** could be used on all platforms where the tilde ~ makes sense. But I know nothing about Macs (although the wife insists on me getting one into the house).

**Comment by Mestelan** [comment] 2018-09-18 21:43
Unfortunately, I cannot reproduce this issue.

I have merged branch **spring**, which uses an alternate REST framework.
Closing this issue; please open a new one, should you experience difficulties after this update.

**Closed by Mestelan** 2018-09-18 21:43 UTC
